# Generated by Django 6.0.3 on 2026-04-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_schedulehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveLoadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('session_data', models.JSONField(default=list)),
                ('avg_cognitive_load', models.FloatField(default=0.5)),
                ('flow_zone_percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_sessions', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='MistakePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('topic_weakness', 'Topic Weakness'), ('difficulty_ceiling', 'Difficulty Ceiling'), ('time_pressure', 'Time Pressure'), ('conceptual_confusion', 'Conceptual Confusion')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('gemini_insight', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_patterns', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_concepts', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_links_from', to='courses.course')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_links_to', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'source_course', 'target_course')},
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetitionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=1)),
                ('repetition_count', models.IntegerField(default=0)),
                ('next_review_date', models.DateField()),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('last_quality', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_cards', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date'],
                'unique_together': {('user', 'course', 'topic')},
            },
        ),
    ]
