# Generated by Django 6.0.3 on 2026-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours_spent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=models.TextField(help_text='Comma separated topics'),
        ),
    ]
