# Generated by Django 6.0.3 on 2026-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_schedule',
            field=models.JSONField(blank=True, help_text='Stored AI generated schedule', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_feedback',
            field=models.TextField(blank=True, help_text='User experience/feedback after exam'),
        ),
    ]
