# Generated by Django 6.0.3 on 2026-04-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_ai_schedule_course_exam_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_data', models.JSONField(help_text='The full schedule JSON')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, help_text='Optional label e.g. Week 1 Plan', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_history', to='courses.course')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
