# Generated by Django 5.2 on 2026-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erroranalysislog',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='erroranalysislog',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
